# Fill this with your own values, save as config.yml

# Your email address. SMTP servers need this.
# I recommend webmaster@yourdomain.com
from_email_address: ...
# If you have a password set on your Redis installation
# (AND YOU SHOULD), set it here to connect
redis_password: ...
# Don't hammer those poor mail servers! You will get banned.
sleep_time: 1
# List of SOCKS5 proxy addresses...
#
# Free ones that might be blacklisted available at: http://www.socks-proxy.net
#
# Format below should be in "socks://[user:pass@]proxyhost[:port]"
proxy_addresses:
  - "socks://localhost"
